name = "topmcqbd"
compatibility_date = "2026-08-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "topmcqbd-db"
database_id = "6aecb56e-a820-45df-948e-641aeaafd219"
